# Generated by Django 4.1.5 on 2023-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
