# Generated by Django 4.1.5 on 2023-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantdb', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
