# Generated by Django 4.1.6 on 2023-02-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergies_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.TimeField()),
                ('table_id', models.IntegerField()),
                ('order_finish', models.BooleanField()),
                ('dish_id', models.IntegerField()),
                ('status_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=20)),
                ('allergies_id', models.ManyToManyField(to='restaurant.allergies')),
            ],
        ),
    ]
