# Generated by Django 4.1.7 on 2023-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.CharField(choices=[('order_in_progress', 'Order in progress'), ('received', 'Received'), ('cooking', 'Cooking'), ('problem', 'Problem'), ('ready', 'Ready')], default=('order_in_progress', 'Order in progress'), max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Order in progress', 'Inprogress'), ('Received', 'Received'), ('Cooking', 'Cooking'), ('Problem', 'Problem'), ('Ready', 'Ready')], default='Order in progress', max_length=20),
        ),
    ]
