# Generated by Django 4.1.7 on 2023-02-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_order_status_id_alter_status_status_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status_id',
            new_name='status',
        ),
    ]
