# Generated by Django 4.1.5 on 2023-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_helpneeded_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cooking',
            field=models.BooleanField(default=False),
        ),
    ]
