# Generated by Django 4.1.5 on 2023-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_helpneeded_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('payment_time', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
