# Generated by Django 4.1.5 on 2023-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_status_cooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='cooking',
        ),
    ]
