# Generated by Django 4.1.5 on 2023-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasePql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cost', models.IntegerField()),
                ('size', models.CharField(max_length=80)),
            ],
        ),
    ]
