# Generated by Django 4.1.5 on 2023-01-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_name', models.CharField(max_length=50)),
                ('Dish_id', models.IntegerField(max_length=3)),
                ('Dish_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
